# Site settings
title: Ayush Goel
description: Computer Scientist
baseurl: ""

timezone: America/New_York

# User settings
username: Ayush Goel
user_description: I am a first year Computer Science Major at Rochester Institute of Technology.
user_title: Computer Scientist
email: ag.goelayush@gmail.com
github_username:  ag-ayush

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src']
include: ['node_modules']
